# audit_deck_pptx.ps1 - geometry and text-overflow audit for pitch/deck.pptx
#
# WHY THIS EXISTS
#     pitch/deck.pptx is generated by pitch/build_deck_pptx.py. The generator
#     places every box at absolute coordinates in a 1280x720 px canvas, so a
#     content edit can silently push text past a box edge or off the slide.
#     Nothing in the Python builder can see the rendered result, so this audit
#     asks PowerPoint itself, via COM, what the renderer actually did:
#
#       1. every shape lies within the slide bounds (nothing off-canvas)
#       2. no shape's rendered text is taller than its own box
#          (TextFrame2.TextRange.BoundHeight vs shape.Height)
#       3. no two text shapes overlap vertically *and* horizontally
#       4. every expected figure is present as an embedded picture
#
#     Read-only: opens the deck, measures, closes. Writes nothing.
#
# Usage (from the repo root):
#     powershell -ExecutionPolicy Bypass -File pitch/audit_deck_pptx.ps1
#
# Exit 0 = clean, exit 1 = at least one problem reported.

$ErrorActionPreference = 'Stop'
$repo  = Split-Path -Parent $PSScriptRoot
$pptx  = Join-Path $repo 'pitch\deck.pptx'
$expectSlides = 11
$expectPics   = 11

if (-not (Test-Path -LiteralPath $pptx)) {
    Write-Output "FAIL: $pptx not found. Run: python pitch/build_deck_pptx.py"
    exit 1
}

Write-Output "== DRISHTI deck PPTX geometry audit =="
Write-Output "FILE: $pptx ($((Get-Item -LiteralPath $pptx).Length) bytes)"

$app = New-Object -ComObject PowerPoint.Application
$pres = $app.Presentations.Open($pptx, $true, $false, $false)   # readonly, untitled=false, withwindow=false
$problems = @()
$nShapes = 0; $nText = 0; $nPics = 0

$slideW = $pres.PageSetup.SlideWidth
$slideH = $pres.PageSetup.SlideHeight
Write-Output ("SLIDE: {0} x {1} pt ({2} slides)" -f $slideW, $slideH, $pres.Slides.Count)

if ($pres.Slides.Count -ne $expectSlides) {
    $problems += "slide count is $($pres.Slides.Count), expected $expectSlides"
}

for ($s = 1; $s -le $pres.Slides.Count; $s++) {
    $slide = $pres.Slides.Item($s)
    $boxes = @()

    for ($i = 1; $i -le $slide.Shapes.Count; $i++) {
        $sh = $slide.Shapes.Item($i)
        $nShapes++
        $L = [double]$sh.Left; $T = [double]$sh.Top
        $W = [double]$sh.Width; $H = [double]$sh.Height
        $R = $L + $W; $B = $T + $H
        $name = $sh.Name

        # 1. off-canvas
        $tol = 0.6
        if ($L -lt -$tol -or $T -lt -$tol -or $R -gt $slideW + $tol -or $B -gt $slideH + $tol) {
            $problems += ("slide {0}: shape '{1}' off-canvas L={2:N1} T={3:N1} R={4:N1} B={5:N1}" -f $s, $name, $L, $T, $R, $B)
        }

        if ($sh.Type -eq 13) { $nPics++ }   # msoPicture

        # text?
        $hasText = $false
        try { $hasText = ($sh.HasTextFrame -eq -1) -and ($sh.TextFrame2.HasText -eq -1) } catch {}
        if ($hasText) {
            $nText++
            $txt = ''
            try { $txt = $sh.TextFrame2.TextRange.Text } catch {}
            $txt = ($txt -replace '\s+', ' ').Trim()
            if ($txt.Length -gt 46) { $txt = $txt.Substring(0, 46) + '...' }

            # 2. rendered text taller than its own box?
            $boundH = 0.0
            try { $boundH = [double]$sh.TextFrame2.TextRange.BoundHeight } catch {}
            if ($boundH -gt 0 -and $boundH -gt $H + 1.5) {
                $over = $boundH - $H
                $problems += ("slide {0}: TEXT OVERFLOW {1:N0}pt on shape '{2}' (box {3:N0}pt, text {4:N0}pt) :: {5}" -f $s, $over, $name, $H, $boundH, $txt)
            }
            $boxes += [pscustomobject]@{ Name = $name; L = $L; T = $T; R = $R; B = $B; Txt = $txt }
        }
    }

    # 3. text-shape overlap (ignore thin rules/decoration: require real area)
    for ($a = 0; $a -lt $boxes.Count; $a++) {
        for ($b = $a + 1; $b -lt $boxes.Count; $b++) {
            $x = $boxes[$a]; $y = $boxes[$b]
            $ovX = [Math]::Min($x.R, $y.R) - [Math]::Max($x.L, $y.L)
            $ovY = [Math]::Min($x.B, $y.B) - [Math]::Max($x.T, $y.T)
            if ($ovX -gt 3 -and $ovY -gt 3) {
                $problems += ("slide {0}: text overlap {1}x{2}pt :: '{3}' vs '{4}'" -f $s, [Math]::Round($ovX), [Math]::Round($ovY), $x.Txt, $y.Txt)
            }
        }
    }
}

Write-Output "SHAPES: $nShapes   text shapes: $nText   pictures: $nPics"
if ($nPics -ne $expectPics) {
    $problems += "expected $expectPics embedded pictures, found $nPics"
}

$pres.Close()
$app.Quit()
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($app) | Out-Null

Write-Output ""
if ($problems.Count -eq 0) {
    Write-Output "ALL DRISHTI DECK PPTX GEOMETRY CHECKS PASS"
    exit 0
} else {
    Write-Output "PROBLEMS: $($problems.Count)"
    $problems | ForEach-Object { Write-Output "  - $_" }
    exit 1
}
