function rec = blankRecord(p, CONFIG)
%BLANKRECORD Create an error/placeholder record
    rec = struct('id', p.id, 'split', p.split, 'imagePath', p.imagePath, ...
        'status', 'error', 'errorMsg', 'not scored', ...
        'predClassName', '', 'predictedGrade', -1, 'predictedGradeLabel', '', ...
        'predictedClassIndex', -1, 'confidence', NaN, 'scores', NaN(1, 5), ...
        'proxyGtReferable', false, 'modelReferable', false, ...
        'proxyPredictionCorrect', false, ...
        'lesionTypes', p.lesionTypes, 'nLesionTypes', p.nLesionTypes, ...
        'massIn', NaN(1, 4), 'point', NaN(1, 4), 'iou', NaN(1, 4), ...
        'iouMass', NaN(1, 4), 'diceMass', NaN(1, 4), 'nMaskPx', zeros(1, 4), ...
        'maskAreaFrac', NaN(1, 4), ...
        'massInAll', NaN, 'pointAll', NaN, 'iouAll', NaN, 'iouMassAll', NaN, ...
        'diceMassAll', NaN, 'nMaskPxAll', 0, 'maskAreaFracAll', NaN, ...
        'nAttnPx', 0, 'massOnRetina', NaN, 'attnOnRetina', NaN, ...
        'retMaskValid', false, 'salMax', NaN, 'salMin', NaN, ...
        'cmapResized', false);
end