classdef RetinaAIApp < matlab.apps.AppBase
%RETINAAIAPP Single-image DR screening demo for DrishtiCare.
%   RetinaAIApp()
%
%   App Designer-style application (programmatic, convertible to .mlapp)
%   that wraps predictSingleFundus() with a clean vertical-flow UI:
%     image upload -> quality check -> DR grade -> Grad-CAM -> report
%
%   ENGINEERING demo tool. NOT a clinical device.

    properties (Access = public)
        UIFigure           matlab.ui.Figure
    end

    properties (Access = private)
        ProjectRoot        char
        CurrentImagePath   char
        CurrentResult      struct

        ImageAxes          matlab.ui.control.UIAxes
        UploadButton       matlab.ui.control.Button
        SampleDropdown     matlab.ui.control.DropDown
        AnalyzeButton      matlab.ui.control.Button

        QualityPanel       matlab.ui.container.Panel
        QualityBadge       matlab.ui.control.Label
        QualityScoreLabel  matlab.ui.control.Label

        GradePanel         matlab.ui.container.Panel
        GradeValueLabel    matlab.ui.control.Label
        GradeNameLabel     matlab.ui.control.Label
        ReferableLabel     matlab.ui.control.Label
        ConfidenceLabel    matlab.ui.control.Label
        CascadeLabel       matlab.ui.control.Label

        GradCAMPanel       matlab.ui.container.Panel
        GradCAMAxes        matlab.ui.control.UIAxes

        ReportPanel        matlab.ui.container.Panel
        ReportTextArea     matlab.ui.control.TextArea
        GenerateReportBtn  matlab.ui.control.Button
        CopyReportBtn      matlab.ui.control.Button

        FooterLabel        matlab.ui.control.Label
        StatusLabel        matlab.ui.control.Label
    end

    methods (Access = public)

        function app = RetinaAIApp()
            appRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            addpath(genpath(appRoot));
            app.ProjectRoot = appRoot;
            app.CurrentImagePath = '';
            app.CurrentResult = struct();
            createComponents(app);
            loadSampleList(app);
            registerApp(app, app.UIFigure);
        end

        function delete(app)
            if isvalid(app.UIFigure)
                delete(app.UIFigure);
            end
        end

    end

    methods (Access = private)

        function createComponents(app)
            app.UIFigure = uifigure('Name', 'RETINA-AI', ...
                'Position', [200 50 520 900], ...
                'Color', [0.96 0.97 0.98], ...
                'Resize', 'off');

            scrollable = uipanel(app.UIFigure, ...
                'Position', [0 0 520 900], ...
                'BackgroundColor', [0.96 0.97 0.98], ...
                'BorderType', 'none', ...
                'Scrollable', 'on');

            createHeader(app, scrollable);
            createImageSection(app, scrollable);
            createControlsSection(app, scrollable);
            createQualitySection(app, scrollable);
            createGradeSection(app, scrollable);
            createGradCAMSection(app, scrollable);
            createReportSection(app, scrollable);
            createFooter(app, scrollable);
        end

        function createHeader(app, parent)
            uilabel(parent, 'Text', 'RETINA-AI', ...
                'Position', [0 850 520 40], ...
                'FontSize', 28, ...
                'FontWeight', 'bold', ...
                'FontColor', [0.13 0.22 0.38], ...
                'HorizontalAlignment', 'center');

            uilabel(parent, 'Text', 'AI Retinal Screening Assistant', ...
                'Position', [0 825 520 25], ...
                'FontSize', 13, ...
                'FontColor', [0.45 0.50 0.56], ...
                'HorizontalAlignment', 'center');
        end

        function createImageSection(app, parent)
            app.ImageAxes = uiaxes(parent, ...
                'Position', [60 660 400 160], ...
                'Box', 'on', ...
                'XTick', [], 'YTick', [], ...
                'BackgroundColor', [1 1 1]);
            title(app.ImageAxes, '');

            text(app.ImageAxes, 0.5, 0.5, 'No image selected', ...
                'Units', 'normalized', ...
                'HorizontalAlignment', 'center', ...
                'FontSize', 12, ...
                'Color', [0.7 0.7 0.7]);
        end

        function createControlsSection(app, parent)
            app.UploadButton = uibutton(parent, 'push', ...
                'Text', 'Upload Image', ...
                'Position', [60 620 160 32], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [0.20 0.40 0.70], ...
                'FontColor', [1 1 1], ...
                'ButtonPushedFcn', @(~,~) app.uploadCallback());

            uilabel(parent, 'Text', 'or select sample:', ...
                'Position', [235 625 90 20], ...
                'FontSize', 11, ...
                'FontColor', [0.45 0.50 0.56]);

            app.SampleDropdown = uidropdown(parent, ...
                'Items', {'(no samples)'}, ...
                'Position', [330 620 130 32], ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~,~) app.sampleCallback());

            app.AnalyzeButton = uibutton(parent, 'push', ...
                'Text', 'ANALYZE IMAGE', ...
                'Position', [60 575 400 38], ...
                'FontSize', 15, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [0.10 0.55 0.35], ...
                'FontColor', [1 1 1], ...
                'Enable', 'off', ...
                'ButtonPushedFcn', @(~,~) app.analyzeCallback());
        end

        function createQualitySection(app, parent)
            app.QualityPanel = uipanel(parent, ...
                'Title', ' Image Quality ', ...
                'Position', [30 490 460 75], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [1 1 1]);

            app.QualityBadge = uilabel(app.QualityPanel, ...
                'Text', '—', ...
                'Position', [15 10 140 35], ...
                'FontSize', 18, ...
                'FontWeight', 'bold', ...
                'FontColor', [0.5 0.5 0.5]);

            app.QualityScoreLabel = uilabel(app.QualityPanel, ...
                'Text', 'Upload an image and click ANALYZE', ...
                'Position', [170 10 270 35], ...
                'FontSize', 11, ...
                'FontColor', [0.5 0.5 0.5], ...
                'VerticalAlignment', 'center');
        end

        function createGradeSection(app, parent)
            app.GradePanel = uipanel(parent, ...
                'Title', ' DR Classification ', ...
                'Position', [30 310 460 170], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [1 1 1]);

            app.GradeValueLabel = uilabel(app.GradePanel, ...
                'Text', '—', ...
                'Position', [20 115 200 40], ...
                'FontSize', 28, ...
                'FontWeight', 'bold', ...
                'FontColor', [0.13 0.22 0.38]);

            app.GradeNameLabel = uilabel(app.GradePanel, ...
                'Text', '', ...
                'Position', [230 115 210 40], ...
                'FontSize', 16, ...
                'FontWeight', 'bold', ...
                'FontColor', [0.30 0.35 0.40], ...
                'VerticalAlignment', 'center');

            app.ReferableLabel = uilabel(app.GradePanel, ...
                'Text', '', ...
                'Position', [20 75 420 30], ...
                'FontSize', 13, ...
                'FontColor', [0.30 0.35 0.40]);

            app.ConfidenceLabel = uilabel(app.GradePanel, ...
                'Text', '', ...
                'Position', [20 45 420 25], ...
                'FontSize', 12, ...
                'FontColor', [0.45 0.50 0.56]);

            app.CascadeLabel = uilabel(app.GradePanel, ...
                'Text', '', ...
                'Position', [20 15 420 25], ...
                'FontSize', 12, ...
                'FontColor', [0.45 0.50 0.56]);
        end

        function createGradCAMSection(app, parent)
            app.GradCAMPanel = uipanel(parent, ...
                'Title', ' Grad-CAM Explanation ', ...
                'Position', [30 170 460 130], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [1 1 1]);

            app.GradCAMAxes = uiaxes(app.GradCAMPanel, ...
                'Position', [10 5 440 100], ...
                'XTick', [], 'YTick', [], ...
                'Box', 'on', ...
                'BackgroundColor', [0.95 0.95 0.95]);
            title(app.GradCAMAxes, '');

            text(app.GradCAMAxes, 0.5, 0.5, 'Awaiting analysis', ...
                'Units', 'normalized', ...
                'HorizontalAlignment', 'center', ...
                'FontSize', 11, ...
                'Color', [0.7 0.7 0.7]);
        end

        function createReportSection(app, parent)
            app.ReportPanel = uipanel(parent, ...
                'Title', ' Report ', ...
                'Position', [30 50 460 110], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [1 1 1]);

            app.ReportTextArea = uitextarea(app.ReportPanel, ...
                'Position', [10 35 440 55], ...
                'FontSize', 10, ...
                'FontName', 'Consolas', ...
                'Editable', 'off', ...
                'Value', {'Analysis report will appear here.'});

            app.GenerateReportBtn = uibutton(app.ReportPanel, 'push', ...
                'Text', 'Save Report', ...
                'Position', [10 5 110 25], ...
                'FontSize', 10, ...
                'ButtonPushedFcn', @(~,~) app.saveReportCallback());

            app.CopyReportBtn = uibutton(app.ReportPanel, 'push', ...
                'Text', 'Copy to Clipboard', ...
                'Position', [130 5 130 25], ...
                'FontSize', 10, ...
                'ButtonPushedFcn', @(~,~) app.copyReportCallback());
        end

        function createFooter(app, parent)
            app.FooterLabel = uilabel(parent, ...
                'Text', 'ENGINEERING DEMO - NOT a clinical device. Thresholds are experimental.', ...
                'Position', [0 20 520 20], ...
                'FontSize', 9, ...
                'FontAngle', 'italic', ...
                'FontColor', [0.65 0.32 0.32], ...
                'HorizontalAlignment', 'center');

            app.StatusLabel = uilabel(parent, ...
                'Text', 'Ready', ...
                'Position', [0 0 520 20], ...
                'FontSize', 10, ...
                'FontColor', [0.45 0.50 0.56], ...
                'HorizontalAlignment', 'center');
        end

        function loadSampleList(app)
            valDir = fullfile(app.ProjectRoot, 'data', 'splits', 'val');
            items = {'(no samples)'};
            if exist(valDir, 'dir')
                classes = {'class_0', 'class_1', 'class_2', 'class_3', 'class_4'};
                labels = {'NoDR', 'Mild', 'Moderate', 'Severe', 'Prolif'};
                for c = 1:numel(classes)
                    d = dir(fullfile(valDir, classes{c}, '*.png'));
                    for i = 1:min(3, numel(d))
                        items{end+1} = sprintf('%s/%s (%s)', classes{c}, d(i).name, labels{c}); %#ok<AGROW>
                    end
                end
            end
            app.SampleDropdown.Items = items;
        end

        function uploadCallback(app)
            [file, path] = uigetfile({'*.png;*.jpg;*.jpeg', 'Fundus images'}, 'Select a fundus image');
            if isequal(file, 0)
                return;
            end
            app.CurrentImagePath = fullfile(path, file);
            showImage(app, app.CurrentImagePath);
            app.AnalyzeButton.Enable = 'on';
            app.StatusLabel.Text = sprintf('Loaded: %s', file);
        end

        function sampleCallback(app)
            val = app.SampleDropdown.Value;
            if strcmp(val, '(no samples)')
                return;
            end
            parts = strsplit(val, '/');
            classFolder = parts{1};
            rest = strsplit(parts{2}, ' ');
            fileName = rest{1};
            app.CurrentImagePath = fullfile(app.ProjectRoot, 'data', 'splits', 'val', classFolder, fileName);
            if exist(app.CurrentImagePath, 'file')
                showImage(app, app.CurrentImagePath);
                app.AnalyzeButton.Enable = 'on';
                app.StatusLabel.Text = sprintf('Loaded: %s', fileName);
            else
                app.StatusLabel.Text = 'Sample file not found.';
            end
        end

        function showImage(app, imgPath)
            try
                img = imread(imgPath);
                imshow(img, 'Parent', app.ImageAxes);
                title(app.ImageAxes, '');
            catch
                app.StatusLabel.Text = 'Failed to load image.';
            end
        end

        function analyzeCallback(app)
            if isempty(app.CurrentImagePath) || ~exist(app.CurrentImagePath, 'file')
                app.StatusLabel.Text = 'No valid image selected.';
                return;
            end

            app.AnalyzeButton.Enable = 'off';
            app.StatusLabel.Text = 'Analyzing...';
            drawnow;

            try
                result = predictSingleFundus(app.CurrentImagePath, ...
                    'ShowFigure', false, 'RunLesions', true, 'RunBranchB', true);
                app.CurrentResult = result;
                displayResults(app, result);
                app.StatusLabel.Text = sprintf('Analysis complete (%.2fs)', result.runtimeSec);
            catch e
                app.StatusLabel.Text = sprintf('Error: %s', e.message);
            end

            app.AnalyzeButton.Enable = 'on';
        end

        function displayResults(app, r)
        end

        function saveReportCallback(app)
            if isempty(app.CurrentResult)
                app.StatusLabel.Text = 'No analysis to save.';
                return;
            end
            [file, path] = uiputfile({'*.txt', 'Text files'}, 'Save Report', 'retina_report.txt');
            if isequal(file, 0)
                return;
            end
            lines = app.ReportTextArea.Value;
            fid = fopen(fullfile(path, file), 'w');
            for i = 1:numel(lines)
                fprintf(fid, '%s\n', lines{i});
            end
            fclose(fid);
            app.StatusLabel.Text = sprintf('Report saved: %s', file);
        end

        function copyReportCallback(app)
            if isempty(app.CurrentResult)
                return;
            end
            lines = app.ReportTextArea.Value;
            text = strjoin(lines, newline);
            clipboard('copy', text);
            app.StatusLabel.Text = 'Report copied to clipboard.';
        end

    end

end