% save_drishti_checkpoint.m
% Write results/V2_DrishtiApp_checkpoint.mat — the MATLAB Drive / repo
% source of truth for the DRISHTI judge-demo app configuration.
%
% Run: matlab -batch "run('src/dashboard/save_drishti_checkpoint.m')"
%
% ENGINEERING demo artifact. NOT a clinical device.

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(projectRoot, 'src')));

qc = defaultQualityConfig();
config = struct( ...
    'appName', 'DRISHTI', ...
    'appClass', 'RetinaAIApp', ...
    'binaryThreshold', 0.60, ...
    'thresholdLocked', true, ...
    'skipModelOnFail', true, ...
    'gradcamLayer', 'res5b_relu', ...
    'qualityConfigVersion', qc.version, ...
    'qualityStatuses', {{'ACCEPT (PASS)', 'BORDERLINE (WARNING)', 'REJECT (FAIL)'}}, ...
    'binaryModel', fullfile(projectRoot, 'data', 'models', ...
        'day7_pretrained_resnet18_binary_stage2.mat'), ...
    'gradeModel', fullfile(projectRoot, 'data', 'models', ...
        'day7_pretrained_resnet18_5class_stage2.mat'));
savedAt = char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

assert(exist(config.binaryModel, 'file') == 2, 'binary model present');
assert(exist(config.gradeModel, 'file') == 2, 'grade model present');

outDir = fullfile(projectRoot, 'results');
if ~exist(outDir, 'dir'), mkdir(outDir); end
outPath = fullfile(outDir, 'V2_DrishtiApp_checkpoint.mat');
save(outPath, 'config', 'savedAt', '-v7.3');
d = dir(outPath);
assert(d.bytes > 0, 'checkpoint non-empty');
fprintf('CHECKPOINT_SAVED %s (%d bytes)\n', outPath, d.bytes);
